// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RosChunkFileData is an autogenerated mock type for the RosChunkFileData type
type RosChunkFileData struct {
	mock.Mock
}
