// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileDataMapper is an autogenerated mock type for the FileDataMapper type
type FileDataMapper struct {
	mock.Mock
}

// GetFileInfo provides a mock function with given fields: name
func (_m *FileDataMapper) GetFileInfo(name string) (uint8, string, error) {
	ret := _m.Called(name)

	var r0 uint8
	if rf, ok := ret.Get(0).(func(string) uint8); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(uint8)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
