// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	chunks "github.com/alunegov/k3archive/models/chunks"

	mock "github.com/stretchr/testify/mock"

	os "os"
)

// ChunkMapper is an autogenerated mock type for the ChunkMapper type
type ChunkMapper struct {
	mock.Mock
}

// Load provides a mock function with given fields: file, chunkInfo
func (_m *ChunkMapper) Load(file *os.File, chunkInfo *chunks.RosChunkFileHeader2) chunks.RosChunkFileData {
	ret := _m.Called(file, chunkInfo)

	var r0 chunks.RosChunkFileData
	if rf, ok := ret.Get(0).(func(*os.File, *chunks.RosChunkFileHeader2) chunks.RosChunkFileData); ok {
		r0 = rf(file, chunkInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chunks.RosChunkFileData)
		}
	}

	return r0
}
