name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.11', '1.12', '1.13']
    steps:
      - uses: actions/checkout@v1

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dest: [rpi, win32, win64]
        include:
          - dest: rpi
            goos: linux
            goarch: arm
            goarm: 6
          - dest: win32
            goos: windows
            goarch: 386
          - dest: win64
            goos: windows
            goarch: amd64
    steps:
      - uses: actions/checkout@v1

      - name: Setup Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: '1.12'

      - name: Build for ${{ matrix.dest }} (with GOARM)
        if: matrix.goarm != null
        run: go build -v
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}

      - name: Build for ${{ matrix.dest }} (without GOARM)
        if: matrix.goarm == null
        run: go build -v
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
